apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: qwerdsa53/user-service:1.1.0
          ports:
            - containerPort: 8082
          env:
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: user-service-config
                  key: REDIS_HOST
            - name: P_URL
              valueFrom:
                secretKeyRef:
                  name: user-service-secret
                  key: P_URL
            - name: P_USERNAME
              valueFrom:
                secretKeyRef:
                  name: user-service-secret
                  key: P_USERNAME
            - name: P_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: user-service-secret
                  key: P_PASSWORD
            - name: SECRET
              valueFrom:
                secretKeyRef:
                  name: user-service-secret
                  key: SECRET
