spring:
  application:
    name: notification-service
  data:
    mongodb:
      host: localhost
      port: 27017
      database: notifications
      username: admin
      password: password
      authentication-database: admin
debug:
  true
server:
  port: 8081