server:
  port: 8080
spring:
  application:
    name: api-gateway
  data:
    redis:
      host: ${REDIS_HOST}
      port: 6379
      ssl:
        enabled: true
  datasource:
    url: ${P_URL}
    username: ${P_USERNAME}
    password: ${P_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
app.secret: ${SECRET}
user:
  service:
    uri: ${USER_SERVICE_URI}
posts:
  service:
    uri: ${POST_SERVICE_URI}
feed:
  service:
    uri: ${FEED_SERVICE_URI}
debug: true