server:
  port: 8080
spring:
  application:
    name: api-gateway
  data:
    redis:
      host: ${REDIS_HOST}
      port: 6379
      ssl:
        enabled: true
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: Post Service
        url: http://localhost:8080/api/v1/posts/v3/api-docs
      - name: User Service
        url: http://localhost:8080/api/v1/user/v3/api-docs
  api-docs:
    enabled: true
    paths-to-match: /**
jwt:
  secret: ${SECRET}
user-service:
  uri: ${USER_SERVICE_URI}
posts-service:
  uri: ${POST_SERVICE_URI}
feed-service:
  uri: ${FEED_SERVICE_URI}
mail-service:
  uri: ${MAIL_SERVICE_URI}
ws-gateway:
  uri: ${WS_GATEWAY_URI}
debug: true