server:
  port: 8080
spring:
  application:
    name: api-gateway
  data:
    redis:
      host: ${REDIS_HOST}
      port: 6379
      ssl:
        enabled: true
jwt:
  secret: ${SECRET}
user-service:
  uri: ${USER_SERVICE_URI}
posts-service:
  uri: ${POST_SERVICE_URI}
feed-service:
  uri: ${FEED_SERVICE_URI}
mail-service:
  uri: ${MAIL_SERVICE_URI}
ws-gateway:
  uri: ${WS_GATEWAY_URI}
debug: true