spring:
  application:
    name: post-service
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: ${P_URL}
    username: ${P_USERNAME}
    password: ${P_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
  #        dialect: org.hibernate.dialect.PostgreSQLDialect
  #        format_sql: true
  #        show_sql: true
  #        use_sql_comments: true
  #        highlight_sql: true
  data:
    redis:
      host: ${REDIS_HOST}
    rest:
      detection-strategy: annotated
springdoc:
  api-docs:
    path: /api/v1/posts/v3/api-docs
logging:
  level:
    org.springdoc.core.utils.SpringDocAnnotationsUtils: ERROR
server:
  port: 8083
debug: true
jwt:
  secret: ${SECRET}

minio:
  bucket: ${MINIO_BUCKET}
  url: ${MINIO_URL}
  accessKey: ${MINIO_ACCESS_KEY}
  secretKey: ${MINIO_SECRET_KEY}