spring:
  application:
    name: file-service
server:
  port: 8086
minio:
  buckets:
    fileBucket: ${MINIO_FILE_BUCKET}
    avatarBucket: ${MINIO_AVATAR_BUCKET}
  url: ${MINIO_URL}
  accessKey: ${MINIO_ACCESS_KEY}
  secretKey: ${MINIO_SECRET_KEY}
debug: true