apiVersion: apps/v1
kind: Deployment
metadata:
  name: posts-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: posts-service
  template:
    metadata:
      labels:
        app: posts-service
    spec:
      containers:
        - name: posts-service
          image: qwerdsa53/post-service:1.0.0
          ports:
            - containerPort: 8083
          env:
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: posts-service-config
                  key: REDIS_HOST
            - name: P_URL
              valueFrom:
                secretKeyRef:
                  name: posts-service-secret
                  key: P_URL
            - name: P_USERNAME
              valueFrom:
                secretKeyRef:
                  name: posts-service-secret
                  key: P_USERNAME
            - name: P_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: posts-service-secret
                  key: P_PASSWORD
            - name: SECRET
              valueFrom:
                secretKeyRef:
                  name: posts-service-secret
                  key: SECRET