spring:
  application:
    name: user-service
  config:
    import:
      - optional:file:user-service/.env[.properties]
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: false
  datasource:
    url: ${P_URL}
    username: ${P_USERNAME}
    password: ${P_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  data:
    rest:
      detection-strategy: annotated
springdoc:
  api-docs:
    path: /api/v1/user/v3/api-docs
server:
  port: 8082
jwt:
  secret: ${SECRET}
mail-service:
  uri: ${MAIL_SERVICE_URI}
redis:
  host: ${REDIS_HOST}
debug: true
