spring:
  application:
    name: user-service
  data:
    redis:
      host: ${REDIS_HOST}
      port: 6379
      ssl:
        enabled: true
  datasource:
    url: ${P_URL}
    username: ${P_USERNAME}
    password: ${P_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8082
debug: true
