apiVersion: apps/v1
kind: Deployment
metadata:
  name: feed-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: feed-service
  template:
    metadata:
      labels:
        app: feed-service
    spec:
      containers:
        - name: feed-service
          image: qwerdsa53/feed-service:1.0.2
          ports:
            - containerPort: 8084
          env:
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: feed-service-config
                  key: REDIS_HOST
            - name: POST_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: feed-service-config
                  key: POST_SERVICE_URL
            - name: P_URL
              valueFrom:
                secretKeyRef:
                  name: feed-service-secret
                  key: P_URL
            - name: P_USERNAME
              valueFrom:
                secretKeyRef:
                  name: feed-service-secret
                  key: P_USERNAME
            - name: P_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: feed-service-secret
                  key: P_PASSWORD
            - name: SECRET
              valueFrom:
                secretKeyRef:
                  name: feed-service-secret
                  key: SECRET