name: Multi-Service CI/CD

on:
  push:
    branches:
      - master
      - test-actions
  pull_request:
    branches:
      - master

jobs:
  check-files:
    runs-on: ubuntu-latest
    outputs:
      api-gateway-changed: ${{ steps.check-api-gateway.outputs.changed }}
      user-service-changed: ${{ steps.check-user-service.outputs.changed }}
      post-service-changed: ${{ steps.check-post-service.outputs.changed }}
      feed-service-changed: ${{ steps.check-feed-service.outputs.changed }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check changes in api-gateway
        id: check-api-gateway
        run: |
          git fetch --depth=2 origin ${{ github.ref }}
          if git diff --name-only HEAD~1 HEAD | grep '^api-gateway/'; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Check changes in user-service
        id: check-user-service
        run: |
          git fetch --depth=2 origin ${{ github.ref }}
          if git diff --name-only HEAD~1 HEAD | grep '^user-service/'; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Check changes in post-service
        id: check-post-service
        run: |
          git fetch --depth=2 origin ${{ github.ref }}
          if git diff --name-only HEAD~1 HEAD | grep '^post-service/'; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Check changes in feed-service
        id: check-feed-service
        run: |
          git fetch --depth=2 origin ${{ github.ref }}
          if git diff --name-only HEAD~1 HEAD | grep '^feed-service/'; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

  api-gateway:
    needs: check-files
    if: needs.check-files.outputs.api-gateway-changed == 'true'
    runs-on: ubuntu-latest
    environment: env

    services:
      postgres:
        image: postgres:13
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: ${{ secrets.P_USERNAME }}
          POSTGRES_PASSWORD: ${{ secrets.P_PASSWORD }}
          POSTGRES_DB: cms

      redis:
        image: redis:6
        ports:
          - 6379:6379
        options: --health-cmd="redis-cli ping || exit 1"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build and Test api-gateway
        working-directory: ./api-gateway
        env:
          SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/cms
          SPRING_DATASOURCE_USERNAME: ${{ secrets.P_USERNAME }}
          SPRING_DATASOURCE_PASSWORD: ${{ secrets.P_PASSWORD }}
          REDIS_HOST: localhost
          REDIS_PORT: 6379
        run: |
          mvn clean install
          mvn test

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Check if Secrets are Accessible
        run: |
          if [ -z "${{ secrets.CLUSTER_ID }}" ]; then echo "CLUSTER_ID is NOT accessible"; else echo "CLUSTER_ID is accessible"; fi
          if [ -z "${{ secrets.DOCKER_HUB_PASSWORD }}" ]; then echo "DOCKER_HUB_PASSWORD is NOT accessible"; else echo "DOCKER_HUB_PASSWORD is accessible"; fi
          if [ -z "${{ secrets.DOCKER_HUB_USERNAME }}" ]; then echo "DOCKER_HUB_USERNAME is NOT accessible"; else echo "DOCKER_HUB_USERNAME is accessible"; fi
          if [ -z "${{ secrets.DOCKER_PASSWORD }}" ]; then echo "DOCKER_PASSWORD is NOT accessible"; else echo "DOCKER_PASSWORD is accessible"; fi
          if [ -z "${{ secrets.DOCKER_USERNAME }}" ]; then echo "DOCKER_USERNAME is NOT accessible"; else echo "DOCKER_USERNAME is accessible"; fi
          if [ -z "${{ secrets.FOLDER_ID }}" ]; then echo "FOLDER_ID is NOT accessible"; else echo "FOLDER_ID is accessible"; fi
          if [ -z "${{ secrets.KUBECONFIG }}" ]; then echo "KUBECONFIG is NOT accessible"; else echo "KUBECONFIG is accessible"; fi
          if [ -z "${{ secrets.P_PASSWORD }}" ]; then echo "P_PASSWORD is NOT accessible"; else echo "P_PASSWORD is accessible"; fi
          if [ -z "${{ secrets.P_USERNAME }}" ]; then echo "P_USERNAME is NOT accessible"; else echo "P_USERNAME is accessible"; fi
          if [ -z "${{ secrets.SECRET }}" ]; then echo "SECRET is NOT accessible"; else echo "SECRET is accessible"; fi
          if [ -z "${{ secrets.YC_KEY_JSON }}" ]; then echo "YC_KEY_JSON is NOT accessible"; else echo "YC_KEY_JSON is accessible"; fi
      
    

      - name: Log in to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

      - name: Build and Push Docker Image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

          IMAGE_NAME="${{ secrets.DOCKER_USERNAME }}/api-gateway"
          LATEST_VERSION=$(curl -s "https://registry.hub.docker.com/v2/repositories/$IMAGE_NAME/tags" | jq -r '.results | map(.name) | map(select(test("^[0-9]+\\.[0-9]+\\.[0-9]+$"))) | sort | last // "0.0.0"')
          echo "Последняя версия: $LATEST_VERSION"

          IFS='.' read -r MAJOR MINOR PATCH <<< "$LATEST_VERSION"
          NEW_VERSION="$MAJOR.$MINOR.$((PATCH + 1))"
          echo "Новая версия: $NEW_VERSION"

          docker build -t $IMAGE_NAME:$NEW_VERSION ./api-gateway
          docker push $IMAGE_NAME:$NEW_VERSION

          echo "image=$IMAGE_NAME:$NEW_VERSION" >> $GITHUB_ENV

      - name: Install Yandex Cloud CLI
        run: |
          curl -sSL https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash
          source "/home/runner/.bashrc

      - name: Deploy to Yandex Cloud Kubernetes
        env:
          YC_KEY_JSON: ${{ secrets.YC_KEY_JSON }}
          CLUSTER_ID: ${{ secrets.CLUSTER_ID }}
          FOLDER_ID: ${{ secrets.FOLDER_ID }}
        run: |
          mkdir -p ~/.config/yandex-cloud
          echo "$YC_KEY_JSON" > ~/.config/yandex-cloud/key.json
          yc config set service-account-key ~/.config/yandex-cloud/key.json
          yc config set folder-id $FOLDER_ID

          KUBECONFIG_PATH=~/.kube/config
          yc managed-kubernetes cluster get-credentials \
            --id $CLUSTER_ID \
            --external \
            --force --kubeconfig $KUBECONFIG_PATH

          kubectl --kubeconfig=$KUBECONFIG_PATH apply -f ./kubernetes/api-gateway-deployment.yaml



  user-service:
    needs: check-files
    if: needs.check-files.outputs.user-service-changed == 'true'
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: ${{ secrets.P_USERNAME }}
          POSTGRES_PASSWORD: ${{ secrets.P_PASSWORD }}
          POSTGRES_DB: cms

      redis:
        image: redis:6
        ports:
          - 6379:6379
        options: --health-cmd="redis-cli ping || exit 1"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build and Test user-service
        working-directory: ./user-service
        env:
          SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/cms
          SPRING_DATASOURCE_USERNAME: ${{ secrets.P_USERNAME }}
          SPRING_DATASOURCE_PASSWORD: ${{ secrets.P_PASSWORD }}
          REDIS_HOST: localhost
          REDIS_PORT: 6379
        run: |
          mvn clean install
          mvn test

  post-service:
    needs: check-files
    if: needs.check-files.outputs.post-service-changed == 'true'
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: ${{ secrets.P_USERNAME }}
          POSTGRES_PASSWORD: ${{ secrets.P_PASSWORD }}
          POSTGRES_DB: cms

      redis:
        image: redis:6
        ports:
          - 6379:6379
        options: --health-cmd="redis-cli ping || exit 1"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build and Test post-service
        working-directory: ./post-service
        env:
          SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/cms
          SPRING_DATASOURCE_USERNAME: ${{ secrets.P_USERNAME }}
          SPRING_DATASOURCE_PASSWORD: ${{ secrets.P_PASSWORD }}
          REDIS_HOST: localhost
          REDIS_PORT: 6379
        run: |
          mvn clean install
          mvn test

  feed-service:
    needs: check-files
    if: needs.check-files.outputs.feed-service-changed == 'true'
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: ${{ secrets.P_USERNAME }}
          POSTGRES_PASSWORD: ${{ secrets.P_PASSWORD }}
          POSTGRES_DB: cms

      redis:
        image: redis:6
        ports:
          - 6379:6379
        options: --health-cmd="redis-cli ping || exit 1"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build and Test feed-service
        working-directory: ./feed-service
        env:
          SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/cms
          SPRING_DATASOURCE_USERNAME: ${{ secrets.P_USERNAME }}
          SPRING_DATASOURCE_PASSWORD: ${{ secrets.P_PASSWORD }}
          REDIS_HOST: localhost
          REDIS_PORT: 6379
        run: |
          mvn clean install
          mvn test
