name: Multi-Service CI/CD

on:
  push:
    branches:
      - master
      - test-actions
  pull_request:
    branches:
      - master

jobs:
  check-files:
    runs-on: ubuntu-latest
    outputs:
      api-gateway-changed: ${{ steps.check-api-gateway.outputs.changed }}
      user-service-changed: ${{ steps.check-user-service.outputs.changed }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check changes in api-gateway
        id: check-api-gateway
        run: |
          if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '^api-gateway/'; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Check changes in user-service
        id: check-user-service
        run: |
          if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '^user-service/'; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

  api-gateway:
    needs: check-files
    if: needs.check-files.outputs.api-gateway-changed == 'true'
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 1423
          POSTGRES_DB: cms

      redis:
        image: redis:6
        ports:
          - 6379:6379
        options: --health-cmd="redis-cli ping || exit 1"

    env:
      P_PASSWORD: 1423
      P_URL: jdbc:postgresql://localhost:5432/cms
      P_USERNAME: postgres
      REDIS_HOST: localhost
      REDIS_PORT: 6379
      SECRET: kzM6i0bTVHVswcm2EWgNwGgyaMVoufz1DhSkWimmjhGSlYeoIr+51jZm6govxPRf80ZSeJ7ILE0aYjpzm9OQgw==

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build api-gateway
        working-directory: ./api-gateway
        run: mvn clean install

      - name: Test api-gateway
        working-directory: ./api-gateway
        env:
          SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/cms
          SPRING_DATASOURCE_USERNAME: postgres
          SPRING_DATASOURCE_PASSWORD: 1423
          REDIS_HOST: localhost
          REDIS_PORT: 6379
        run: mvn test

  user-service:
    needs: check-files
    if: needs.check-files.outputs.user-service-changed == 'true'
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 1423
          POSTGRES_DB: CMS

      redis:
        image: redis:6
        ports:
          - 6379:6379
        options: --health-cmd="redis-cli ping || exit 1"

    env:
      P_PASSWORD: 1423
      P_URL: jdbc:postgresql://localhost:5432/CMS
      P_USERNAME: postgres
      REDIS_HOST: localhost
      REDIS_PORT: 6379
      SECRET: kzM6i0bTVHVswcm2EWgNwGgyaMVoufz1DhSkWimmjhGSlYeoIr+51jZm6govxPRf80ZSeJ7ILE0aYjpzm9OQgw==

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build user-service
        working-directory: ./user-service
        run: mvn clean install

      - name: Test user-service
        working-directory: ./user-service
        env:
          SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/CMS
          SPRING_DATASOURCE_USERNAME: postgres
          SPRING_DATASOURCE_PASSWORD: 1423
          REDIS_HOST: localhost
          REDIS_PORT: 6379
        run: mvn test
