apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: qwerdsa53/api-gateway:1.1.4
          ports:
            - containerPort: 8080
          env:
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: api-gateway-config
                  key: REDIS_HOST
            - name: USER_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: api-gateway-config
                  key: USER_SERVICE_URL
            - name: POST_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: api-gateway-config
                  key: POST_SERVICE_URL
            - name: FEED_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: api-gateway-config
                  key: FEED_SERVICE_URL

            - name: P_URL
              valueFrom:
                secretKeyRef:
                  name: api-gateway-secret
                  key: P_URL
            - name: P_USERNAME
              valueFrom:
                secretKeyRef:
                  name: api-gateway-secret
                  key: P_USERNAME
            - name: P_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: api-gateway-secret
                  key: P_PASSWORD
            - name: SECRET
              valueFrom:
                secretKeyRef:
                  name: api-gateway-secret
                  key: SECRET